/*
 * This file is generated by jOOQ.
 */
package com.mjcc.message_board.jooq.tables.records;


import com.mjcc.message_board.jooq.tables.TReply;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TReplyRecord extends UpdatableRecordImpl<TReplyRecord> implements Record12<Integer, String, String, String, String, Short, Integer, String, Integer, Integer, Integer, LocalDateTime> {

    private static final long serialVersionUID = -824959868;

    /**
     * Setter for <code>public.t_reply.lr_id</code>. 回复id编号
     */
    public void setLrId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.t_reply.lr_id</code>. 回复id编号
     */
    public Integer getLrId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.t_reply.lr_openid</code>. 回复人opendi
     */
    public void setLrOpenid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.t_reply.lr_openid</code>. 回复人opendi
     */
    public String getLrOpenid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.t_reply.lr_name</code>. 回复人名字
     */
    public void setLrName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.t_reply.lr_name</code>. 回复人名字
     */
    public String getLrName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.t_reply.lr_head_imgurl</code>. 回复人头像
     */
    public void setLrHeadImgurl(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.t_reply.lr_head_imgurl</code>. 回复人头像
     */
    public String getLrHeadImgurl() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.t_reply.lr_content</code>. 评论内容
     */
    public void setLrContent(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.t_reply.lr_content</code>. 评论内容
     */
    public String getLrContent() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.t_reply.lr_type</code>. 留言类型,对评论还是回复
     */
    public void setLrType(Short value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.t_reply.lr_type</code>. 留言类型,对评论还是回复
     */
    public Short getLrType() {
        return (Short) get(5);
    }

    /**
     * Setter for <code>public.t_reply.lr_dest_id</code>. 回复目标id lr_type == comment ? 评论表id : 回复表id
     */
    public void setLrDestId(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.t_reply.lr_dest_id</code>. 回复目标id lr_type == comment ? 评论表id : 回复表id
     */
    public Integer getLrDestId() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>public.t_reply.lr_dest_openid</code>. 评论人的openid
     */
    public void setLrDestOpenid(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.t_reply.lr_dest_openid</code>. 评论人的openid
     */
    public String getLrDestOpenid() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.t_reply.lr_comment_id</code>. 挂在那个根评论下
     */
    public void setLrCommentId(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.t_reply.lr_comment_id</code>. 挂在那个根评论下
     */
    public Integer getLrCommentId() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>public.t_reply.lr_zan</code>. 被赞数
     */
    public void setLrZan(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.t_reply.lr_zan</code>. 被赞数
     */
    public Integer getLrZan() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>public.t_reply.lr_cai</code>. 被踩数
     */
    public void setLrCai(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.t_reply.lr_cai</code>. 被踩数
     */
    public Integer getLrCai() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>public.t_reply.lr_date</code>. 创建时间
     */
    public void setLrDate(LocalDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.t_reply.lr_date</code>. 创建时间
     */
    public LocalDateTime getLrDate() {
        return (LocalDateTime) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<Integer, String, String, String, String, Short, Integer, String, Integer, Integer, Integer, LocalDateTime> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<Integer, String, String, String, String, Short, Integer, String, Integer, Integer, Integer, LocalDateTime> valuesRow() {
        return (Row12) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TReply.T_REPLY.LR_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TReply.T_REPLY.LR_OPENID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TReply.T_REPLY.LR_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TReply.T_REPLY.LR_HEAD_IMGURL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TReply.T_REPLY.LR_CONTENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field6() {
        return TReply.T_REPLY.LR_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return TReply.T_REPLY.LR_DEST_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return TReply.T_REPLY.LR_DEST_OPENID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return TReply.T_REPLY.LR_COMMENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field10() {
        return TReply.T_REPLY.LR_ZAN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field11() {
        return TReply.T_REPLY.LR_CAI;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field12() {
        return TReply.T_REPLY.LR_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getLrId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getLrOpenid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getLrName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getLrHeadImgurl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getLrContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short component6() {
        return getLrType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component7() {
        return getLrDestId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getLrDestOpenid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component9() {
        return getLrCommentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component10() {
        return getLrZan();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component11() {
        return getLrCai();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component12() {
        return getLrDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getLrId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getLrOpenid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getLrName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getLrHeadImgurl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getLrContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value6() {
        return getLrType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getLrDestId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getLrDestOpenid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getLrCommentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value10() {
        return getLrZan();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value11() {
        return getLrCai();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value12() {
        return getLrDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TReplyRecord value1(Integer value) {
        setLrId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TReplyRecord value2(String value) {
        setLrOpenid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TReplyRecord value3(String value) {
        setLrName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TReplyRecord value4(String value) {
        setLrHeadImgurl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TReplyRecord value5(String value) {
        setLrContent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TReplyRecord value6(Short value) {
        setLrType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TReplyRecord value7(Integer value) {
        setLrDestId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TReplyRecord value8(String value) {
        setLrDestOpenid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TReplyRecord value9(Integer value) {
        setLrCommentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TReplyRecord value10(Integer value) {
        setLrZan(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TReplyRecord value11(Integer value) {
        setLrCai(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TReplyRecord value12(LocalDateTime value) {
        setLrDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TReplyRecord values(Integer value1, String value2, String value3, String value4, String value5, Short value6, Integer value7, String value8, Integer value9, Integer value10, Integer value11, LocalDateTime value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TReplyRecord
     */
    public TReplyRecord() {
        super(TReply.T_REPLY);
    }

    /**
     * Create a detached, initialised TReplyRecord
     */
    public TReplyRecord(Integer lrId, String lrOpenid, String lrName, String lrHeadImgurl, String lrContent, Short lrType, Integer lrDestId, String lrDestOpenid, Integer lrCommentId, Integer lrZan, Integer lrCai, LocalDateTime lrDate) {
        super(TReply.T_REPLY);

        set(0, lrId);
        set(1, lrOpenid);
        set(2, lrName);
        set(3, lrHeadImgurl);
        set(4, lrContent);
        set(5, lrType);
        set(6, lrDestId);
        set(7, lrDestOpenid);
        set(8, lrCommentId);
        set(9, lrZan);
        set(10, lrCai);
        set(11, lrDate);
    }
}
