/*
 * This file is generated by jOOQ.
 */
package com.mjcc.message_board.jooq.tables.records;


import com.mjcc.message_board.jooq.tables.TUserInfo;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TUserInfoRecord extends UpdatableRecordImpl<TUserInfoRecord> implements Record10<String, String, Short, String, String, String, String, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = -295972544;

    /**
     * Setter for <code>public.t_user_info.openid</code>. 用户openid
     */
    public void setOpenid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.t_user_info.openid</code>. 用户openid
     */
    public String getOpenid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.t_user_info.nickname</code>. 用户名称
     */
    public void setNickname(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.t_user_info.nickname</code>. 用户名称
     */
    public String getNickname() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.t_user_info.sex</code>. 用户性别
     */
    public void setSex(Short value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.t_user_info.sex</code>. 用户性别
     */
    public Short getSex() {
        return (Short) get(2);
    }

    /**
     * Setter for <code>public.t_user_info.m_province</code>. 省份
     */
    public void setMProvince(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.t_user_info.m_province</code>. 省份
     */
    public String getMProvince() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.t_user_info.m_city</code>. 城市
     */
    public void setMCity(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.t_user_info.m_city</code>. 城市
     */
    public String getMCity() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.t_user_info.m_country</code>. 国家
     */
    public void setMCountry(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.t_user_info.m_country</code>. 国家
     */
    public String getMCountry() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.t_user_info.m_language</code>. 用户语言
     */
    public void setMLanguage(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.t_user_info.m_language</code>. 用户语言
     */
    public String getMLanguage() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.t_user_info.head_imgurl</code>. 用户头像
     */
    public void setHeadImgurl(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.t_user_info.head_imgurl</code>. 用户头像
     */
    public String getHeadImgurl() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.t_user_info.create_time</code>. 创建时间
     */
    public void setCreateTime(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.t_user_info.create_time</code>. 创建时间
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>public.t_user_info.update_time</code>. 更新时间
     */
    public void setUpdateTime(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.t_user_info.update_time</code>. 更新时间
     */
    public LocalDateTime getUpdateTime() {
        return (LocalDateTime) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<String, String, Short, String, String, String, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<String, String, Short, String, String, String, String, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return TUserInfo.T_USER_INFO.OPENID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TUserInfo.T_USER_INFO.NICKNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field3() {
        return TUserInfo.T_USER_INFO.SEX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TUserInfo.T_USER_INFO.M_PROVINCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TUserInfo.T_USER_INFO.M_CITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return TUserInfo.T_USER_INFO.M_COUNTRY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return TUserInfo.T_USER_INFO.M_LANGUAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return TUserInfo.T_USER_INFO.HEAD_IMGURL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field9() {
        return TUserInfo.T_USER_INFO.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field10() {
        return TUserInfo.T_USER_INFO.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getOpenid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getNickname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short component3() {
        return getSex();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getMProvince();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getMCity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getMCountry();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getMLanguage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getHeadImgurl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component9() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component10() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getOpenid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getNickname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value3() {
        return getSex();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getMProvince();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getMCity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getMCountry();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getMLanguage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getHeadImgurl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value9() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value10() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUserInfoRecord value1(String value) {
        setOpenid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUserInfoRecord value2(String value) {
        setNickname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUserInfoRecord value3(Short value) {
        setSex(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUserInfoRecord value4(String value) {
        setMProvince(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUserInfoRecord value5(String value) {
        setMCity(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUserInfoRecord value6(String value) {
        setMCountry(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUserInfoRecord value7(String value) {
        setMLanguage(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUserInfoRecord value8(String value) {
        setHeadImgurl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUserInfoRecord value9(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUserInfoRecord value10(LocalDateTime value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUserInfoRecord values(String value1, String value2, Short value3, String value4, String value5, String value6, String value7, String value8, LocalDateTime value9, LocalDateTime value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TUserInfoRecord
     */
    public TUserInfoRecord() {
        super(TUserInfo.T_USER_INFO);
    }

    /**
     * Create a detached, initialised TUserInfoRecord
     */
    public TUserInfoRecord(String openid, String nickname, Short sex, String mProvince, String mCity, String mCountry, String mLanguage, String headImgurl, LocalDateTime createTime, LocalDateTime updateTime) {
        super(TUserInfo.T_USER_INFO);

        set(0, openid);
        set(1, nickname);
        set(2, sex);
        set(3, mProvince);
        set(4, mCity);
        set(5, mCountry);
        set(6, mLanguage);
        set(7, headImgurl);
        set(8, createTime);
        set(9, updateTime);
    }
}
