/*
 * This file is generated by jOOQ.
 */
package com.mjcc.message_board.jooq.tables.records;


import com.mjcc.message_board.jooq.tables.TWords;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TWordsRecord extends UpdatableRecordImpl<TWordsRecord> implements Record10<Integer, String, String, String, String, Integer, Short, Integer, Integer, LocalDateTime> {

    private static final long serialVersionUID = 748277219;

    /**
     * Setter for <code>public.t_words.lw_id</code>. 评论id编号
     */
    public void setLwId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.t_words.lw_id</code>. 评论id编号
     */
    public Integer getLwId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.t_words.lw_openid</code>. 评论人的openid
     */
    public void setLwOpenid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.t_words.lw_openid</code>. 评论人的openid
     */
    public String getLwOpenid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.t_words.lw_name</code>. 评论人的的名字
     */
    public void setLwName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.t_words.lw_name</code>. 评论人的的名字
     */
    public String getLwName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.t_words.lw_head_imgurl</code>. 评论用户的头像
     */
    public void setLwHeadImgurl(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.t_words.lw_head_imgurl</code>. 评论用户的头像
     */
    public String getLwHeadImgurl() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.t_words.lw_content</code>. 评论内容
     */
    public void setLwContent(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.t_words.lw_content</code>. 评论内容
     */
    public String getLwContent() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.t_words.lw_for_topic_id</code>. 那个主题留言
     */
    public void setLwForTopicId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.t_words.lw_for_topic_id</code>. 那个主题留言
     */
    public Integer getLwForTopicId() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.t_words.lw_select</code>. 是否是精选留言
     */
    public void setLwSelect(Short value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.t_words.lw_select</code>. 是否是精选留言
     */
    public Short getLwSelect() {
        return (Short) get(6);
    }

    /**
     * Setter for <code>public.t_words.lw_zan</code>. 被赞数
     */
    public void setLwZan(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.t_words.lw_zan</code>. 被赞数
     */
    public Integer getLwZan() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>public.t_words.lw_cai</code>. 被踩数
     */
    public void setLwCai(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.t_words.lw_cai</code>. 被踩数
     */
    public Integer getLwCai() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>public.t_words.lw_date</code>. 创建时间
     */
    public void setLwDate(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.t_words.lw_date</code>. 创建时间
     */
    public LocalDateTime getLwDate() {
        return (LocalDateTime) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, String, String, String, String, Integer, Short, Integer, Integer, LocalDateTime> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, String, String, String, String, Integer, Short, Integer, Integer, LocalDateTime> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TWords.T_WORDS.LW_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TWords.T_WORDS.LW_OPENID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TWords.T_WORDS.LW_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TWords.T_WORDS.LW_HEAD_IMGURL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TWords.T_WORDS.LW_CONTENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return TWords.T_WORDS.LW_FOR_TOPIC_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field7() {
        return TWords.T_WORDS.LW_SELECT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return TWords.T_WORDS.LW_ZAN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return TWords.T_WORDS.LW_CAI;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field10() {
        return TWords.T_WORDS.LW_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getLwId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getLwOpenid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getLwName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getLwHeadImgurl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getLwContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getLwForTopicId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short component7() {
        return getLwSelect();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component8() {
        return getLwZan();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component9() {
        return getLwCai();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component10() {
        return getLwDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getLwId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getLwOpenid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getLwName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getLwHeadImgurl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getLwContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getLwForTopicId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value7() {
        return getLwSelect();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getLwZan();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getLwCai();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value10() {
        return getLwDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TWordsRecord value1(Integer value) {
        setLwId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TWordsRecord value2(String value) {
        setLwOpenid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TWordsRecord value3(String value) {
        setLwName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TWordsRecord value4(String value) {
        setLwHeadImgurl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TWordsRecord value5(String value) {
        setLwContent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TWordsRecord value6(Integer value) {
        setLwForTopicId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TWordsRecord value7(Short value) {
        setLwSelect(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TWordsRecord value8(Integer value) {
        setLwZan(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TWordsRecord value9(Integer value) {
        setLwCai(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TWordsRecord value10(LocalDateTime value) {
        setLwDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TWordsRecord values(Integer value1, String value2, String value3, String value4, String value5, Integer value6, Short value7, Integer value8, Integer value9, LocalDateTime value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TWordsRecord
     */
    public TWordsRecord() {
        super(TWords.T_WORDS);
    }

    /**
     * Create a detached, initialised TWordsRecord
     */
    public TWordsRecord(Integer lwId, String lwOpenid, String lwName, String lwHeadImgurl, String lwContent, Integer lwForTopicId, Short lwSelect, Integer lwZan, Integer lwCai, LocalDateTime lwDate) {
        super(TWords.T_WORDS);

        set(0, lwId);
        set(1, lwOpenid);
        set(2, lwName);
        set(3, lwHeadImgurl);
        set(4, lwContent);
        set(5, lwForTopicId);
        set(6, lwSelect);
        set(7, lwZan);
        set(8, lwCai);
        set(9, lwDate);
    }
}
