/*
 * This file is generated by jOOQ.
 */
package com.mjcc.message_board.jooq.tables.daos;


import com.mjcc.message_board.jooq.tables.PunishCategory;
import com.mjcc.message_board.jooq.tables.records.PunishCategoryRecord;

import java.time.LocalDateTime;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * 惩罚类目表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PunishCategoryDao extends DAOImpl<PunishCategoryRecord, com.mjcc.message_board.jooq.tables.pojos.PunishCategory, Integer> {

    /**
     * Create a new PunishCategoryDao without any configuration
     */
    public PunishCategoryDao() {
        super(PunishCategory.PUNISH_CATEGORY, com.mjcc.message_board.jooq.tables.pojos.PunishCategory.class);
    }

    /**
     * Create a new PunishCategoryDao with an attached configuration
     */
    public PunishCategoryDao(Configuration configuration) {
        super(PunishCategory.PUNISH_CATEGORY, com.mjcc.message_board.jooq.tables.pojos.PunishCategory.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.mjcc.message_board.jooq.tables.pojos.PunishCategory object) {
        return object.getCategoryId();
    }

    /**
     * Fetch records that have <code>category_id IN (values)</code>
     */
    public List<com.mjcc.message_board.jooq.tables.pojos.PunishCategory> fetchByCategoryId(Integer... values) {
        return fetch(PunishCategory.PUNISH_CATEGORY.CATEGORY_ID, values);
    }

    /**
     * Fetch a unique record that has <code>category_id = value</code>
     */
    public com.mjcc.message_board.jooq.tables.pojos.PunishCategory fetchOneByCategoryId(Integer value) {
        return fetchOne(PunishCategory.PUNISH_CATEGORY.CATEGORY_ID, value);
    }

    /**
     * Fetch records that have <code>category_name IN (values)</code>
     */
    public List<com.mjcc.message_board.jooq.tables.pojos.PunishCategory> fetchByCategoryName(String... values) {
        return fetch(PunishCategory.PUNISH_CATEGORY.CATEGORY_NAME, values);
    }

    /**
     * Fetch records that have <code>create_time IN (values)</code>
     */
    public List<com.mjcc.message_board.jooq.tables.pojos.PunishCategory> fetchByCreateTime(LocalDateTime... values) {
        return fetch(PunishCategory.PUNISH_CATEGORY.CREATE_TIME, values);
    }
}
