/*
 * This file is generated by jOOQ.
 */
package com.mjcc.message_board.jooq.tables.daos;


import com.mjcc.message_board.jooq.tables.TReply;
import com.mjcc.message_board.jooq.tables.records.TReplyRecord;

import java.time.LocalDateTime;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TReplyDao extends DAOImpl<TReplyRecord, com.mjcc.message_board.jooq.tables.pojos.TReply, Integer> {

    /**
     * Create a new TReplyDao without any configuration
     */
    public TReplyDao() {
        super(TReply.T_REPLY, com.mjcc.message_board.jooq.tables.pojos.TReply.class);
    }

    /**
     * Create a new TReplyDao with an attached configuration
     */
    public TReplyDao(Configuration configuration) {
        super(TReply.T_REPLY, com.mjcc.message_board.jooq.tables.pojos.TReply.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.mjcc.message_board.jooq.tables.pojos.TReply object) {
        return object.getLrId();
    }

    /**
     * Fetch records that have <code>lr_id IN (values)</code>
     */
    public List<com.mjcc.message_board.jooq.tables.pojos.TReply> fetchByLrId(Integer... values) {
        return fetch(TReply.T_REPLY.LR_ID, values);
    }

    /**
     * Fetch a unique record that has <code>lr_id = value</code>
     */
    public com.mjcc.message_board.jooq.tables.pojos.TReply fetchOneByLrId(Integer value) {
        return fetchOne(TReply.T_REPLY.LR_ID, value);
    }

    /**
     * Fetch records that have <code>lr_openid IN (values)</code>
     */
    public List<com.mjcc.message_board.jooq.tables.pojos.TReply> fetchByLrOpenid(String... values) {
        return fetch(TReply.T_REPLY.LR_OPENID, values);
    }

    /**
     * Fetch records that have <code>lr_name IN (values)</code>
     */
    public List<com.mjcc.message_board.jooq.tables.pojos.TReply> fetchByLrName(String... values) {
        return fetch(TReply.T_REPLY.LR_NAME, values);
    }

    /**
     * Fetch records that have <code>lr_head_imgurl IN (values)</code>
     */
    public List<com.mjcc.message_board.jooq.tables.pojos.TReply> fetchByLrHeadImgurl(String... values) {
        return fetch(TReply.T_REPLY.LR_HEAD_IMGURL, values);
    }

    /**
     * Fetch records that have <code>lr_content IN (values)</code>
     */
    public List<com.mjcc.message_board.jooq.tables.pojos.TReply> fetchByLrContent(String... values) {
        return fetch(TReply.T_REPLY.LR_CONTENT, values);
    }

    /**
     * Fetch records that have <code>lr_type IN (values)</code>
     */
    public List<com.mjcc.message_board.jooq.tables.pojos.TReply> fetchByLrType(Short... values) {
        return fetch(TReply.T_REPLY.LR_TYPE, values);
    }

    /**
     * Fetch records that have <code>lr_dest_id IN (values)</code>
     */
    public List<com.mjcc.message_board.jooq.tables.pojos.TReply> fetchByLrDestId(Integer... values) {
        return fetch(TReply.T_REPLY.LR_DEST_ID, values);
    }

    /**
     * Fetch records that have <code>lr_dest_openid IN (values)</code>
     */
    public List<com.mjcc.message_board.jooq.tables.pojos.TReply> fetchByLrDestOpenid(String... values) {
        return fetch(TReply.T_REPLY.LR_DEST_OPENID, values);
    }

    /**
     * Fetch records that have <code>lr_comment_id IN (values)</code>
     */
    public List<com.mjcc.message_board.jooq.tables.pojos.TReply> fetchByLrCommentId(Integer... values) {
        return fetch(TReply.T_REPLY.LR_COMMENT_ID, values);
    }

    /**
     * Fetch records that have <code>lr_zan IN (values)</code>
     */
    public List<com.mjcc.message_board.jooq.tables.pojos.TReply> fetchByLrZan(Integer... values) {
        return fetch(TReply.T_REPLY.LR_ZAN, values);
    }

    /**
     * Fetch records that have <code>lr_cai IN (values)</code>
     */
    public List<com.mjcc.message_board.jooq.tables.pojos.TReply> fetchByLrCai(Integer... values) {
        return fetch(TReply.T_REPLY.LR_CAI, values);
    }

    /**
     * Fetch records that have <code>lr_date IN (values)</code>
     */
    public List<com.mjcc.message_board.jooq.tables.pojos.TReply> fetchByLrDate(LocalDateTime... values) {
        return fetch(TReply.T_REPLY.LR_DATE, values);
    }
}
