/*
 * This file is generated by jOOQ.
 */
package com.mjcc.message_board.jooq.tables.daos;


import com.mjcc.message_board.jooq.tables.TUserInfo;
import com.mjcc.message_board.jooq.tables.records.TUserInfoRecord;

import java.time.LocalDateTime;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TUserInfoDao extends DAOImpl<TUserInfoRecord, com.mjcc.message_board.jooq.tables.pojos.TUserInfo, String> {

    /**
     * Create a new TUserInfoDao without any configuration
     */
    public TUserInfoDao() {
        super(TUserInfo.T_USER_INFO, com.mjcc.message_board.jooq.tables.pojos.TUserInfo.class);
    }

    /**
     * Create a new TUserInfoDao with an attached configuration
     */
    public TUserInfoDao(Configuration configuration) {
        super(TUserInfo.T_USER_INFO, com.mjcc.message_board.jooq.tables.pojos.TUserInfo.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(com.mjcc.message_board.jooq.tables.pojos.TUserInfo object) {
        return object.getOpenid();
    }

    /**
     * Fetch records that have <code>openid IN (values)</code>
     */
    public List<com.mjcc.message_board.jooq.tables.pojos.TUserInfo> fetchByOpenid(String... values) {
        return fetch(TUserInfo.T_USER_INFO.OPENID, values);
    }

    /**
     * Fetch a unique record that has <code>openid = value</code>
     */
    public com.mjcc.message_board.jooq.tables.pojos.TUserInfo fetchOneByOpenid(String value) {
        return fetchOne(TUserInfo.T_USER_INFO.OPENID, value);
    }

    /**
     * Fetch records that have <code>nickname IN (values)</code>
     */
    public List<com.mjcc.message_board.jooq.tables.pojos.TUserInfo> fetchByNickname(String... values) {
        return fetch(TUserInfo.T_USER_INFO.NICKNAME, values);
    }

    /**
     * Fetch records that have <code>sex IN (values)</code>
     */
    public List<com.mjcc.message_board.jooq.tables.pojos.TUserInfo> fetchBySex(Short... values) {
        return fetch(TUserInfo.T_USER_INFO.SEX, values);
    }

    /**
     * Fetch records that have <code>m_province IN (values)</code>
     */
    public List<com.mjcc.message_board.jooq.tables.pojos.TUserInfo> fetchByMProvince(String... values) {
        return fetch(TUserInfo.T_USER_INFO.M_PROVINCE, values);
    }

    /**
     * Fetch records that have <code>m_city IN (values)</code>
     */
    public List<com.mjcc.message_board.jooq.tables.pojos.TUserInfo> fetchByMCity(String... values) {
        return fetch(TUserInfo.T_USER_INFO.M_CITY, values);
    }

    /**
     * Fetch records that have <code>m_country IN (values)</code>
     */
    public List<com.mjcc.message_board.jooq.tables.pojos.TUserInfo> fetchByMCountry(String... values) {
        return fetch(TUserInfo.T_USER_INFO.M_COUNTRY, values);
    }

    /**
     * Fetch records that have <code>m_language IN (values)</code>
     */
    public List<com.mjcc.message_board.jooq.tables.pojos.TUserInfo> fetchByMLanguage(String... values) {
        return fetch(TUserInfo.T_USER_INFO.M_LANGUAGE, values);
    }

    /**
     * Fetch records that have <code>head_imgurl IN (values)</code>
     */
    public List<com.mjcc.message_board.jooq.tables.pojos.TUserInfo> fetchByHeadImgurl(String... values) {
        return fetch(TUserInfo.T_USER_INFO.HEAD_IMGURL, values);
    }

    /**
     * Fetch records that have <code>create_time IN (values)</code>
     */
    public List<com.mjcc.message_board.jooq.tables.pojos.TUserInfo> fetchByCreateTime(LocalDateTime... values) {
        return fetch(TUserInfo.T_USER_INFO.CREATE_TIME, values);
    }

    /**
     * Fetch records that have <code>update_time IN (values)</code>
     */
    public List<com.mjcc.message_board.jooq.tables.pojos.TUserInfo> fetchByUpdateTime(LocalDateTime... values) {
        return fetch(TUserInfo.T_USER_INFO.UPDATE_TIME, values);
    }
}
