/*
 * This file is generated by jOOQ.
 */
package com.mjcc.message_board.jooq.tables.daos;


import com.mjcc.message_board.jooq.tables.TWords;
import com.mjcc.message_board.jooq.tables.records.TWordsRecord;

import java.time.LocalDateTime;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TWordsDao extends DAOImpl<TWordsRecord, com.mjcc.message_board.jooq.tables.pojos.TWords, Integer> {

    /**
     * Create a new TWordsDao without any configuration
     */
    public TWordsDao() {
        super(TWords.T_WORDS, com.mjcc.message_board.jooq.tables.pojos.TWords.class);
    }

    /**
     * Create a new TWordsDao with an attached configuration
     */
    public TWordsDao(Configuration configuration) {
        super(TWords.T_WORDS, com.mjcc.message_board.jooq.tables.pojos.TWords.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.mjcc.message_board.jooq.tables.pojos.TWords object) {
        return object.getLwId();
    }

    /**
     * Fetch records that have <code>lw_id IN (values)</code>
     */
    public List<com.mjcc.message_board.jooq.tables.pojos.TWords> fetchByLwId(Integer... values) {
        return fetch(TWords.T_WORDS.LW_ID, values);
    }

    /**
     * Fetch a unique record that has <code>lw_id = value</code>
     */
    public com.mjcc.message_board.jooq.tables.pojos.TWords fetchOneByLwId(Integer value) {
        return fetchOne(TWords.T_WORDS.LW_ID, value);
    }

    /**
     * Fetch records that have <code>lw_openid IN (values)</code>
     */
    public List<com.mjcc.message_board.jooq.tables.pojos.TWords> fetchByLwOpenid(String... values) {
        return fetch(TWords.T_WORDS.LW_OPENID, values);
    }

    /**
     * Fetch records that have <code>lw_name IN (values)</code>
     */
    public List<com.mjcc.message_board.jooq.tables.pojos.TWords> fetchByLwName(String... values) {
        return fetch(TWords.T_WORDS.LW_NAME, values);
    }

    /**
     * Fetch records that have <code>lw_head_imgurl IN (values)</code>
     */
    public List<com.mjcc.message_board.jooq.tables.pojos.TWords> fetchByLwHeadImgurl(String... values) {
        return fetch(TWords.T_WORDS.LW_HEAD_IMGURL, values);
    }

    /**
     * Fetch records that have <code>lw_content IN (values)</code>
     */
    public List<com.mjcc.message_board.jooq.tables.pojos.TWords> fetchByLwContent(String... values) {
        return fetch(TWords.T_WORDS.LW_CONTENT, values);
    }

    /**
     * Fetch records that have <code>lw_for_topic_id IN (values)</code>
     */
    public List<com.mjcc.message_board.jooq.tables.pojos.TWords> fetchByLwForTopicId(Integer... values) {
        return fetch(TWords.T_WORDS.LW_FOR_TOPIC_ID, values);
    }

    /**
     * Fetch records that have <code>lw_select IN (values)</code>
     */
    public List<com.mjcc.message_board.jooq.tables.pojos.TWords> fetchByLwSelect(Short... values) {
        return fetch(TWords.T_WORDS.LW_SELECT, values);
    }

    /**
     * Fetch records that have <code>lw_zan IN (values)</code>
     */
    public List<com.mjcc.message_board.jooq.tables.pojos.TWords> fetchByLwZan(Integer... values) {
        return fetch(TWords.T_WORDS.LW_ZAN, values);
    }

    /**
     * Fetch records that have <code>lw_cai IN (values)</code>
     */
    public List<com.mjcc.message_board.jooq.tables.pojos.TWords> fetchByLwCai(Integer... values) {
        return fetch(TWords.T_WORDS.LW_CAI, values);
    }

    /**
     * Fetch records that have <code>lw_date IN (values)</code>
     */
    public List<com.mjcc.message_board.jooq.tables.pojos.TWords> fetchByLwDate(LocalDateTime... values) {
        return fetch(TWords.T_WORDS.LW_DATE, values);
    }
}
