/*
 * This file is generated by jOOQ.
 */
package com.mjcc.message_board.jooq.tables.daos;


import com.mjcc.message_board.jooq.tables.TWordAreaInfo;
import com.mjcc.message_board.jooq.tables.records.TWordAreaInfoRecord;

import java.time.LocalDateTime;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TWordAreaInfoDao extends DAOImpl<TWordAreaInfoRecord, com.mjcc.message_board.jooq.tables.pojos.TWordAreaInfo, Integer> {

    /**
     * Create a new TWordAreaInfoDao without any configuration
     */
    public TWordAreaInfoDao() {
        super(TWordAreaInfo.T_WORD_AREA_INFO, com.mjcc.message_board.jooq.tables.pojos.TWordAreaInfo.class);
    }

    /**
     * Create a new TWordAreaInfoDao with an attached configuration
     */
    public TWordAreaInfoDao(Configuration configuration) {
        super(TWordAreaInfo.T_WORD_AREA_INFO, com.mjcc.message_board.jooq.tables.pojos.TWordAreaInfo.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.mjcc.message_board.jooq.tables.pojos.TWordAreaInfo object) {
        return object.getArticleId();
    }

    /**
     * Fetch records that have <code>article_id IN (values)</code>
     */
    public List<com.mjcc.message_board.jooq.tables.pojos.TWordAreaInfo> fetchByArticleId(Integer... values) {
        return fetch(TWordAreaInfo.T_WORD_AREA_INFO.ARTICLE_ID, values);
    }

    /**
     * Fetch a unique record that has <code>article_id = value</code>
     */
    public com.mjcc.message_board.jooq.tables.pojos.TWordAreaInfo fetchOneByArticleId(Integer value) {
        return fetchOne(TWordAreaInfo.T_WORD_AREA_INFO.ARTICLE_ID, value);
    }

    /**
     * Fetch records that have <code>openid IN (values)</code>
     */
    public List<com.mjcc.message_board.jooq.tables.pojos.TWordAreaInfo> fetchByOpenid(String... values) {
        return fetch(TWordAreaInfo.T_WORD_AREA_INFO.OPENID, values);
    }

    /**
     * Fetch records that have <code>article_title IN (values)</code>
     */
    public List<com.mjcc.message_board.jooq.tables.pojos.TWordAreaInfo> fetchByArticleTitle(String... values) {
        return fetch(TWordAreaInfo.T_WORD_AREA_INFO.ARTICLE_TITLE, values);
    }

    /**
     * Fetch records that have <code>article_url IN (values)</code>
     */
    public List<com.mjcc.message_board.jooq.tables.pojos.TWordAreaInfo> fetchByArticleUrl(String... values) {
        return fetch(TWordAreaInfo.T_WORD_AREA_INFO.ARTICLE_URL, values);
    }

    /**
     * Fetch records that have <code>article_img IN (values)</code>
     */
    public List<com.mjcc.message_board.jooq.tables.pojos.TWordAreaInfo> fetchByArticleImg(String... values) {
        return fetch(TWordAreaInfo.T_WORD_AREA_INFO.ARTICLE_IMG, values);
    }

    /**
     * Fetch records that have <code>publicname IN (values)</code>
     */
    public List<com.mjcc.message_board.jooq.tables.pojos.TWordAreaInfo> fetchByPublicname(String... values) {
        return fetch(TWordAreaInfo.T_WORD_AREA_INFO.PUBLICNAME, values);
    }

    /**
     * Fetch records that have <code>description IN (values)</code>
     */
    public List<com.mjcc.message_board.jooq.tables.pojos.TWordAreaInfo> fetchByDescription(String... values) {
        return fetch(TWordAreaInfo.T_WORD_AREA_INFO.DESCRIPTION, values);
    }

    /**
     * Fetch records that have <code>create_time IN (values)</code>
     */
    public List<com.mjcc.message_board.jooq.tables.pojos.TWordAreaInfo> fetchByCreateTime(LocalDateTime... values) {
        return fetch(TWordAreaInfo.T_WORD_AREA_INFO.CREATE_TIME, values);
    }
}
