/*
 * This file is generated by jOOQ.
 */
package com.mjcc.message_board.jooq.tables.daos;


import com.mjcc.message_board.jooq.tables.UserShareInfo;
import com.mjcc.message_board.jooq.tables.records.UserShareInfoRecord;

import java.time.LocalDateTime;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * 用户分享信息表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserShareInfoDao extends DAOImpl<UserShareInfoRecord, com.mjcc.message_board.jooq.tables.pojos.UserShareInfo, String> {

    /**
     * Create a new UserShareInfoDao without any configuration
     */
    public UserShareInfoDao() {
        super(UserShareInfo.USER_SHARE_INFO, com.mjcc.message_board.jooq.tables.pojos.UserShareInfo.class);
    }

    /**
     * Create a new UserShareInfoDao with an attached configuration
     */
    public UserShareInfoDao(Configuration configuration) {
        super(UserShareInfo.USER_SHARE_INFO, com.mjcc.message_board.jooq.tables.pojos.UserShareInfo.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(com.mjcc.message_board.jooq.tables.pojos.UserShareInfo object) {
        return object.getShareOpenid();
    }

    /**
     * Fetch records that have <code>share_openid IN (values)</code>
     */
    public List<com.mjcc.message_board.jooq.tables.pojos.UserShareInfo> fetchByShareOpenid(String... values) {
        return fetch(UserShareInfo.USER_SHARE_INFO.SHARE_OPENID, values);
    }

    /**
     * Fetch a unique record that has <code>share_openid = value</code>
     */
    public com.mjcc.message_board.jooq.tables.pojos.UserShareInfo fetchOneByShareOpenid(String value) {
        return fetchOne(UserShareInfo.USER_SHARE_INFO.SHARE_OPENID, value);
    }

    /**
     * Fetch records that have <code>share_status IN (values)</code>
     */
    public List<com.mjcc.message_board.jooq.tables.pojos.UserShareInfo> fetchByShareStatus(Short... values) {
        return fetch(UserShareInfo.USER_SHARE_INFO.SHARE_STATUS, values);
    }

    /**
     * Fetch records that have <code>target_one IN (values)</code>
     */
    public List<com.mjcc.message_board.jooq.tables.pojos.UserShareInfo> fetchByTargetOne(String... values) {
        return fetch(UserShareInfo.USER_SHARE_INFO.TARGET_ONE, values);
    }

    /**
     * Fetch records that have <code>target_two IN (values)</code>
     */
    public List<com.mjcc.message_board.jooq.tables.pojos.UserShareInfo> fetchByTargetTwo(String... values) {
        return fetch(UserShareInfo.USER_SHARE_INFO.TARGET_TWO, values);
    }

    /**
     * Fetch records that have <code>target_three IN (values)</code>
     */
    public List<com.mjcc.message_board.jooq.tables.pojos.UserShareInfo> fetchByTargetThree(String... values) {
        return fetch(UserShareInfo.USER_SHARE_INFO.TARGET_THREE, values);
    }

    /**
     * Fetch records that have <code>create_time IN (values)</code>
     */
    public List<com.mjcc.message_board.jooq.tables.pojos.UserShareInfo> fetchByCreateTime(LocalDateTime... values) {
        return fetch(UserShareInfo.USER_SHARE_INFO.CREATE_TIME, values);
    }
}
