/*
 * This file is generated by jOOQ.
 */
package com.mjcc.message_board.jooq.tables.daos;


import com.mjcc.message_board.jooq.tables.Witness;
import com.mjcc.message_board.jooq.tables.records.WitnessRecord;

import java.time.LocalDateTime;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * 分享关联表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WitnessDao extends DAOImpl<WitnessRecord, com.mjcc.message_board.jooq.tables.pojos.Witness, String> {

    /**
     * Create a new WitnessDao without any configuration
     */
    public WitnessDao() {
        super(Witness.WITNESS, com.mjcc.message_board.jooq.tables.pojos.Witness.class);
    }

    /**
     * Create a new WitnessDao with an attached configuration
     */
    public WitnessDao(Configuration configuration) {
        super(Witness.WITNESS, com.mjcc.message_board.jooq.tables.pojos.Witness.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(com.mjcc.message_board.jooq.tables.pojos.Witness object) {
        return object.getShareOpenid();
    }

    /**
     * Fetch records that have <code>share_openid IN (values)</code>
     */
    public List<com.mjcc.message_board.jooq.tables.pojos.Witness> fetchByShareOpenid(String... values) {
        return fetch(Witness.WITNESS.SHARE_OPENID, values);
    }

    /**
     * Fetch a unique record that has <code>share_openid = value</code>
     */
    public com.mjcc.message_board.jooq.tables.pojos.Witness fetchOneByShareOpenid(String value) {
        return fetchOne(Witness.WITNESS.SHARE_OPENID, value);
    }

    /**
     * Fetch records that have <code>witness_openid IN (values)</code>
     */
    public List<com.mjcc.message_board.jooq.tables.pojos.Witness> fetchByWitnessOpenid(String... values) {
        return fetch(Witness.WITNESS.WITNESS_OPENID, values);
    }

    /**
     * Fetch records that have <code>category_id IN (values)</code>
     */
    public List<com.mjcc.message_board.jooq.tables.pojos.Witness> fetchByCategoryId(Integer... values) {
        return fetch(Witness.WITNESS.CATEGORY_ID, values);
    }

    /**
     * Fetch records that have <code>create_time IN (values)</code>
     */
    public List<com.mjcc.message_board.jooq.tables.pojos.Witness> fetchByCreateTime(LocalDateTime... values) {
        return fetch(Witness.WITNESS.CREATE_TIME, values);
    }
}
