/*
 * This file is generated by jOOQ.
 */
package com.mjcc.message_board.jooq.tables;


import com.mjcc.message_board.jooq.Indexes;
import com.mjcc.message_board.jooq.Keys;
import com.mjcc.message_board.jooq.Public;
import com.mjcc.message_board.jooq.tables.records.PunishCategoryRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * 惩罚类目表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PunishCategory extends TableImpl<PunishCategoryRecord> {

    private static final long serialVersionUID = 947373664;

    /**
     * The reference instance of <code>public.punish_category</code>
     */
    public static final PunishCategory PUNISH_CATEGORY = new PunishCategory();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PunishCategoryRecord> getRecordType() {
        return PunishCategoryRecord.class;
    }

    /**
     * The column <code>public.punish_category.category_id</code>. 类目id
     */
    public final TableField<PunishCategoryRecord, Integer> CATEGORY_ID = createField("category_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "类目id");

    /**
     * The column <code>public.punish_category.category_name</code>. 类目名称
     */
    public final TableField<PunishCategoryRecord, String> CATEGORY_NAME = createField("category_name", org.jooq.impl.SQLDataType.VARCHAR(512).nullable(false), this, "类目名称");

    /**
     * The column <code>public.punish_category.create_time</code>. 创建时间
     */
    public final TableField<PunishCategoryRecord, LocalDateTime> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "创建时间");

    /**
     * Create a <code>public.punish_category</code> table reference
     */
    public PunishCategory() {
        this(DSL.name("punish_category"), null);
    }

    /**
     * Create an aliased <code>public.punish_category</code> table reference
     */
    public PunishCategory(String alias) {
        this(DSL.name(alias), PUNISH_CATEGORY);
    }

    /**
     * Create an aliased <code>public.punish_category</code> table reference
     */
    public PunishCategory(Name alias) {
        this(alias, PUNISH_CATEGORY);
    }

    private PunishCategory(Name alias, Table<PunishCategoryRecord> aliased) {
        this(alias, aliased, null);
    }

    private PunishCategory(Name alias, Table<PunishCategoryRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("惩罚类目表"));
    }

    public <O extends Record> PunishCategory(Table<O> child, ForeignKey<O, PunishCategoryRecord> key) {
        super(child, key, PUNISH_CATEGORY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PUNISH_CATEGORY_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<PunishCategoryRecord> getPrimaryKey() {
        return Keys.PUNISH_CATEGORY_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<PunishCategoryRecord>> getKeys() {
        return Arrays.<UniqueKey<PunishCategoryRecord>>asList(Keys.PUNISH_CATEGORY_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PunishCategory as(String alias) {
        return new PunishCategory(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PunishCategory as(Name alias) {
        return new PunishCategory(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public PunishCategory rename(String name) {
        return new PunishCategory(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PunishCategory rename(Name name) {
        return new PunishCategory(name, null);
    }
}
