/*
 * This file is generated by jOOQ.
 */
package com.mjcc.message_board.jooq.tables;


import com.mjcc.message_board.jooq.Indexes;
import com.mjcc.message_board.jooq.Keys;
import com.mjcc.message_board.jooq.Public;
import com.mjcc.message_board.jooq.tables.records.TUserInfoRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TUserInfo extends TableImpl<TUserInfoRecord> {

    private static final long serialVersionUID = -844178856;

    /**
     * The reference instance of <code>public.t_user_info</code>
     */
    public static final TUserInfo T_USER_INFO = new TUserInfo();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TUserInfoRecord> getRecordType() {
        return TUserInfoRecord.class;
    }

    /**
     * The column <code>public.t_user_info.openid</code>. 用户openid
     */
    public final TableField<TUserInfoRecord, String> OPENID = createField("openid", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "用户openid");

    /**
     * The column <code>public.t_user_info.nickname</code>. 用户名称
     */
    public final TableField<TUserInfoRecord, String> NICKNAME = createField("nickname", org.jooq.impl.SQLDataType.VARCHAR(128).nullable(false), this, "用户名称");

    /**
     * The column <code>public.t_user_info.sex</code>. 用户性别
     */
    public final TableField<TUserInfoRecord, Short> SEX = createField("sex", org.jooq.impl.SQLDataType.SMALLINT, this, "用户性别");

    /**
     * The column <code>public.t_user_info.m_province</code>. 省份
     */
    public final TableField<TUserInfoRecord, String> M_PROVINCE = createField("m_province", org.jooq.impl.SQLDataType.VARCHAR(40).defaultValue(org.jooq.impl.DSL.field("NULL::character varying", org.jooq.impl.SQLDataType.VARCHAR)), this, "省份");

    /**
     * The column <code>public.t_user_info.m_city</code>. 城市
     */
    public final TableField<TUserInfoRecord, String> M_CITY = createField("m_city", org.jooq.impl.SQLDataType.VARCHAR(50).defaultValue(org.jooq.impl.DSL.field("NULL::character varying", org.jooq.impl.SQLDataType.VARCHAR)), this, "城市");

    /**
     * The column <code>public.t_user_info.m_country</code>. 国家
     */
    public final TableField<TUserInfoRecord, String> M_COUNTRY = createField("m_country", org.jooq.impl.SQLDataType.VARCHAR(40).defaultValue(org.jooq.impl.DSL.field("NULL::character varying", org.jooq.impl.SQLDataType.VARCHAR)), this, "国家");

    /**
     * The column <code>public.t_user_info.m_language</code>. 用户语言
     */
    public final TableField<TUserInfoRecord, String> M_LANGUAGE = createField("m_language", org.jooq.impl.SQLDataType.VARCHAR(32).defaultValue(org.jooq.impl.DSL.field("NULL::character varying", org.jooq.impl.SQLDataType.VARCHAR)), this, "用户语言");

    /**
     * The column <code>public.t_user_info.head_imgurl</code>. 用户头像
     */
    public final TableField<TUserInfoRecord, String> HEAD_IMGURL = createField("head_imgurl", org.jooq.impl.SQLDataType.VARCHAR(512).nullable(false), this, "用户头像");

    /**
     * The column <code>public.t_user_info.create_time</code>. 创建时间
     */
    public final TableField<TUserInfoRecord, LocalDateTime> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "创建时间");

    /**
     * The column <code>public.t_user_info.update_time</code>. 更新时间
     */
    public final TableField<TUserInfoRecord, LocalDateTime> UPDATE_TIME = createField("update_time", org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false), this, "更新时间");

    /**
     * Create a <code>public.t_user_info</code> table reference
     */
    public TUserInfo() {
        this(DSL.name("t_user_info"), null);
    }

    /**
     * Create an aliased <code>public.t_user_info</code> table reference
     */
    public TUserInfo(String alias) {
        this(DSL.name(alias), T_USER_INFO);
    }

    /**
     * Create an aliased <code>public.t_user_info</code> table reference
     */
    public TUserInfo(Name alias) {
        this(alias, T_USER_INFO);
    }

    private TUserInfo(Name alias, Table<TUserInfoRecord> aliased) {
        this(alias, aliased, null);
    }

    private TUserInfo(Name alias, Table<TUserInfoRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> TUserInfo(Table<O> child, ForeignKey<O, TUserInfoRecord> key) {
        super(child, key, T_USER_INFO);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.T_USER_INFO_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TUserInfoRecord> getPrimaryKey() {
        return Keys.T_USER_INFO_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TUserInfoRecord>> getKeys() {
        return Arrays.<UniqueKey<TUserInfoRecord>>asList(Keys.T_USER_INFO_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUserInfo as(String alias) {
        return new TUserInfo(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TUserInfo as(Name alias) {
        return new TUserInfo(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TUserInfo rename(String name) {
        return new TUserInfo(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TUserInfo rename(Name name) {
        return new TUserInfo(name, null);
    }
}
