/*
 * This file is generated by jOOQ.
 */
package com.mjcc.message_board.jooq.tables;


import com.mjcc.message_board.jooq.Indexes;
import com.mjcc.message_board.jooq.Keys;
import com.mjcc.message_board.jooq.Public;
import com.mjcc.message_board.jooq.tables.records.TWordAreaInfoRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TWordAreaInfo extends TableImpl<TWordAreaInfoRecord> {

    private static final long serialVersionUID = 2141917427;

    /**
     * The reference instance of <code>public.t_word_area_info</code>
     */
    public static final TWordAreaInfo T_WORD_AREA_INFO = new TWordAreaInfo();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TWordAreaInfoRecord> getRecordType() {
        return TWordAreaInfoRecord.class;
    }

    /**
     * The column <code>public.t_word_area_info.article_id</code>. id
     */
    public final TableField<TWordAreaInfoRecord, Integer> ARTICLE_ID = createField("article_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('t_word_area_info_article_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "id");

    /**
     * The column <code>public.t_word_area_info.openid</code>. 用户openid
     */
    public final TableField<TWordAreaInfoRecord, String> OPENID = createField("openid", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "用户openid");

    /**
     * The column <code>public.t_word_area_info.article_title</code>. 文章标题
     */
    public final TableField<TWordAreaInfoRecord, String> ARTICLE_TITLE = createField("article_title", org.jooq.impl.SQLDataType.VARCHAR(128).nullable(false), this, "文章标题");

    /**
     * The column <code>public.t_word_area_info.article_url</code>. 文章链接
     */
    public final TableField<TWordAreaInfoRecord, String> ARTICLE_URL = createField("article_url", org.jooq.impl.SQLDataType.VARCHAR(512), this, "文章链接");

    /**
     * The column <code>public.t_word_area_info.article_img</code>. 文章图片
     */
    public final TableField<TWordAreaInfoRecord, String> ARTICLE_IMG = createField("article_img", org.jooq.impl.SQLDataType.VARCHAR(512), this, "文章图片");

    /**
     * The column <code>public.t_word_area_info.publicname</code>. 公众号名称
     */
    public final TableField<TWordAreaInfoRecord, String> PUBLICNAME = createField("publicname", org.jooq.impl.SQLDataType.VARCHAR(128), this, "公众号名称");

    /**
     * The column <code>public.t_word_area_info.description</code>. 描述
     */
    public final TableField<TWordAreaInfoRecord, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR(128), this, "描述");

    /**
     * The column <code>public.t_word_area_info.create_time</code>. 创建时间
     */
    public final TableField<TWordAreaInfoRecord, LocalDateTime> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "创建时间");

    /**
     * Create a <code>public.t_word_area_info</code> table reference
     */
    public TWordAreaInfo() {
        this(DSL.name("t_word_area_info"), null);
    }

    /**
     * Create an aliased <code>public.t_word_area_info</code> table reference
     */
    public TWordAreaInfo(String alias) {
        this(DSL.name(alias), T_WORD_AREA_INFO);
    }

    /**
     * Create an aliased <code>public.t_word_area_info</code> table reference
     */
    public TWordAreaInfo(Name alias) {
        this(alias, T_WORD_AREA_INFO);
    }

    private TWordAreaInfo(Name alias, Table<TWordAreaInfoRecord> aliased) {
        this(alias, aliased, null);
    }

    private TWordAreaInfo(Name alias, Table<TWordAreaInfoRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> TWordAreaInfo(Table<O> child, ForeignKey<O, TWordAreaInfoRecord> key) {
        super(child, key, T_WORD_AREA_INFO);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.T_WORD_AREA_INFO_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TWordAreaInfoRecord, Integer> getIdentity() {
        return Keys.IDENTITY_T_WORD_AREA_INFO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TWordAreaInfoRecord> getPrimaryKey() {
        return Keys.T_WORD_AREA_INFO_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TWordAreaInfoRecord>> getKeys() {
        return Arrays.<UniqueKey<TWordAreaInfoRecord>>asList(Keys.T_WORD_AREA_INFO_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TWordAreaInfo as(String alias) {
        return new TWordAreaInfo(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TWordAreaInfo as(Name alias) {
        return new TWordAreaInfo(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TWordAreaInfo rename(String name) {
        return new TWordAreaInfo(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TWordAreaInfo rename(Name name) {
        return new TWordAreaInfo(name, null);
    }
}
