/*
 * This file is generated by jOOQ.
 */
package com.mjcc.message_board.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TReply implements Serializable {

    private static final long serialVersionUID = -1653780308;

    private Integer       lrId;
    private String        lrOpenid;
    private String        lrName;
    private String        lrHeadImgurl;
    private String        lrContent;
    private Short         lrType;
    private Integer       lrDestId;
    private String        lrDestOpenid;
    private Integer       lrCommentId;
    private Integer       lrZan;
    private Integer       lrCai;
    private LocalDateTime lrDate;

    public TReply() {}

    public TReply(TReply value) {
        this.lrId = value.lrId;
        this.lrOpenid = value.lrOpenid;
        this.lrName = value.lrName;
        this.lrHeadImgurl = value.lrHeadImgurl;
        this.lrContent = value.lrContent;
        this.lrType = value.lrType;
        this.lrDestId = value.lrDestId;
        this.lrDestOpenid = value.lrDestOpenid;
        this.lrCommentId = value.lrCommentId;
        this.lrZan = value.lrZan;
        this.lrCai = value.lrCai;
        this.lrDate = value.lrDate;
    }

    public TReply(
        Integer       lrId,
        String        lrOpenid,
        String        lrName,
        String        lrHeadImgurl,
        String        lrContent,
        Short         lrType,
        Integer       lrDestId,
        String        lrDestOpenid,
        Integer       lrCommentId,
        Integer       lrZan,
        Integer       lrCai,
        LocalDateTime lrDate
    ) {
        this.lrId = lrId;
        this.lrOpenid = lrOpenid;
        this.lrName = lrName;
        this.lrHeadImgurl = lrHeadImgurl;
        this.lrContent = lrContent;
        this.lrType = lrType;
        this.lrDestId = lrDestId;
        this.lrDestOpenid = lrDestOpenid;
        this.lrCommentId = lrCommentId;
        this.lrZan = lrZan;
        this.lrCai = lrCai;
        this.lrDate = lrDate;
    }

    public Integer getLrId() {
        return this.lrId;
    }

    public void setLrId(Integer lrId) {
        this.lrId = lrId;
    }

    public String getLrOpenid() {
        return this.lrOpenid;
    }

    public void setLrOpenid(String lrOpenid) {
        this.lrOpenid = lrOpenid;
    }

    public String getLrName() {
        return this.lrName;
    }

    public void setLrName(String lrName) {
        this.lrName = lrName;
    }

    public String getLrHeadImgurl() {
        return this.lrHeadImgurl;
    }

    public void setLrHeadImgurl(String lrHeadImgurl) {
        this.lrHeadImgurl = lrHeadImgurl;
    }

    public String getLrContent() {
        return this.lrContent;
    }

    public void setLrContent(String lrContent) {
        this.lrContent = lrContent;
    }

    public Short getLrType() {
        return this.lrType;
    }

    public void setLrType(Short lrType) {
        this.lrType = lrType;
    }

    public Integer getLrDestId() {
        return this.lrDestId;
    }

    public void setLrDestId(Integer lrDestId) {
        this.lrDestId = lrDestId;
    }

    public String getLrDestOpenid() {
        return this.lrDestOpenid;
    }

    public void setLrDestOpenid(String lrDestOpenid) {
        this.lrDestOpenid = lrDestOpenid;
    }

    public Integer getLrCommentId() {
        return this.lrCommentId;
    }

    public void setLrCommentId(Integer lrCommentId) {
        this.lrCommentId = lrCommentId;
    }

    public Integer getLrZan() {
        return this.lrZan;
    }

    public void setLrZan(Integer lrZan) {
        this.lrZan = lrZan;
    }

    public Integer getLrCai() {
        return this.lrCai;
    }

    public void setLrCai(Integer lrCai) {
        this.lrCai = lrCai;
    }

    public LocalDateTime getLrDate() {
        return this.lrDate;
    }

    public void setLrDate(LocalDateTime lrDate) {
        this.lrDate = lrDate;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TReply (");

        sb.append(lrId);
        sb.append(", ").append(lrOpenid);
        sb.append(", ").append(lrName);
        sb.append(", ").append(lrHeadImgurl);
        sb.append(", ").append(lrContent);
        sb.append(", ").append(lrType);
        sb.append(", ").append(lrDestId);
        sb.append(", ").append(lrDestOpenid);
        sb.append(", ").append(lrCommentId);
        sb.append(", ").append(lrZan);
        sb.append(", ").append(lrCai);
        sb.append(", ").append(lrDate);

        sb.append(")");
        return sb.toString();
    }
}
