/*
 * This file is generated by jOOQ.
 */
package com.mjcc.message_board.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TUserInfo implements Serializable {

    private static final long serialVersionUID = -2104613409;

    private String        openid;
    private String        nickname;
    private Short         sex;
    private String        mProvince;
    private String        mCity;
    private String        mCountry;
    private String        mLanguage;
    private String        headImgurl;
    private LocalDateTime createTime;
    private LocalDateTime updateTime;

    public TUserInfo() {}

    public TUserInfo(TUserInfo value) {
        this.openid = value.openid;
        this.nickname = value.nickname;
        this.sex = value.sex;
        this.mProvince = value.mProvince;
        this.mCity = value.mCity;
        this.mCountry = value.mCountry;
        this.mLanguage = value.mLanguage;
        this.headImgurl = value.headImgurl;
        this.createTime = value.createTime;
        this.updateTime = value.updateTime;
    }

    public TUserInfo(
        String        openid,
        String        nickname,
        Short         sex,
        String        mProvince,
        String        mCity,
        String        mCountry,
        String        mLanguage,
        String        headImgurl,
        LocalDateTime createTime,
        LocalDateTime updateTime
    ) {
        this.openid = openid;
        this.nickname = nickname;
        this.sex = sex;
        this.mProvince = mProvince;
        this.mCity = mCity;
        this.mCountry = mCountry;
        this.mLanguage = mLanguage;
        this.headImgurl = headImgurl;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    public String getOpenid() {
        return this.openid;
    }

    public void setOpenid(String openid) {
        this.openid = openid;
    }

    public String getNickname() {
        return this.nickname;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    public Short getSex() {
        return this.sex;
    }

    public void setSex(Short sex) {
        this.sex = sex;
    }

    public String getMProvince() {
        return this.mProvince;
    }

    public void setMProvince(String mProvince) {
        this.mProvince = mProvince;
    }

    public String getMCity() {
        return this.mCity;
    }

    public void setMCity(String mCity) {
        this.mCity = mCity;
    }

    public String getMCountry() {
        return this.mCountry;
    }

    public void setMCountry(String mCountry) {
        this.mCountry = mCountry;
    }

    public String getMLanguage() {
        return this.mLanguage;
    }

    public void setMLanguage(String mLanguage) {
        this.mLanguage = mLanguage;
    }

    public String getHeadImgurl() {
        return this.headImgurl;
    }

    public void setHeadImgurl(String headImgurl) {
        this.headImgurl = headImgurl;
    }

    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    public LocalDateTime getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TUserInfo (");

        sb.append(openid);
        sb.append(", ").append(nickname);
        sb.append(", ").append(sex);
        sb.append(", ").append(mProvince);
        sb.append(", ").append(mCity);
        sb.append(", ").append(mCountry);
        sb.append(", ").append(mLanguage);
        sb.append(", ").append(headImgurl);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateTime);

        sb.append(")");
        return sb.toString();
    }
}
