/*
 * This file is generated by jOOQ.
 */
package com.mjcc.message_board.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * 用户分享信息表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserShareInfo implements Serializable {

    private static final long serialVersionUID = 167083990;

    private String        shareOpenid;
    private Short         shareStatus;
    private String        targetOne;
    private String        targetTwo;
    private String        targetThree;
    private LocalDateTime createTime;

    public UserShareInfo() {}

    public UserShareInfo(UserShareInfo value) {
        this.shareOpenid = value.shareOpenid;
        this.shareStatus = value.shareStatus;
        this.targetOne = value.targetOne;
        this.targetTwo = value.targetTwo;
        this.targetThree = value.targetThree;
        this.createTime = value.createTime;
    }

    public UserShareInfo(
        String        shareOpenid,
        Short         shareStatus,
        String        targetOne,
        String        targetTwo,
        String        targetThree,
        LocalDateTime createTime
    ) {
        this.shareOpenid = shareOpenid;
        this.shareStatus = shareStatus;
        this.targetOne = targetOne;
        this.targetTwo = targetTwo;
        this.targetThree = targetThree;
        this.createTime = createTime;
    }

    public String getShareOpenid() {
        return this.shareOpenid;
    }

    public void setShareOpenid(String shareOpenid) {
        this.shareOpenid = shareOpenid;
    }

    public Short getShareStatus() {
        return this.shareStatus;
    }

    public void setShareStatus(Short shareStatus) {
        this.shareStatus = shareStatus;
    }

    public String getTargetOne() {
        return this.targetOne;
    }

    public void setTargetOne(String targetOne) {
        this.targetOne = targetOne;
    }

    public String getTargetTwo() {
        return this.targetTwo;
    }

    public void setTargetTwo(String targetTwo) {
        this.targetTwo = targetTwo;
    }

    public String getTargetThree() {
        return this.targetThree;
    }

    public void setTargetThree(String targetThree) {
        this.targetThree = targetThree;
    }

    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserShareInfo (");

        sb.append(shareOpenid);
        sb.append(", ").append(shareStatus);
        sb.append(", ").append(targetOne);
        sb.append(", ").append(targetTwo);
        sb.append(", ").append(targetThree);
        sb.append(", ").append(createTime);

        sb.append(")");
        return sb.toString();
    }
}
