/*
 * This file is generated by jOOQ.
 */
package com.mjcc.message_board.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * 分享关联表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Witness implements Serializable {

    private static final long serialVersionUID = 1226705863;

    private String        shareOpenid;
    private String        witnessOpenid;
    private Integer       categoryId;
    private LocalDateTime createTime;

    public Witness() {}

    public Witness(Witness value) {
        this.shareOpenid = value.shareOpenid;
        this.witnessOpenid = value.witnessOpenid;
        this.categoryId = value.categoryId;
        this.createTime = value.createTime;
    }

    public Witness(
        String        shareOpenid,
        String        witnessOpenid,
        Integer       categoryId,
        LocalDateTime createTime
    ) {
        this.shareOpenid = shareOpenid;
        this.witnessOpenid = witnessOpenid;
        this.categoryId = categoryId;
        this.createTime = createTime;
    }

    public String getShareOpenid() {
        return this.shareOpenid;
    }

    public void setShareOpenid(String shareOpenid) {
        this.shareOpenid = shareOpenid;
    }

    public String getWitnessOpenid() {
        return this.witnessOpenid;
    }

    public void setWitnessOpenid(String witnessOpenid) {
        this.witnessOpenid = witnessOpenid;
    }

    public Integer getCategoryId() {
        return this.categoryId;
    }

    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Witness (");

        sb.append(shareOpenid);
        sb.append(", ").append(witnessOpenid);
        sb.append(", ").append(categoryId);
        sb.append(", ").append(createTime);

        sb.append(")");
        return sb.toString();
    }
}
