/*
 * This file is generated by jOOQ.
 */
package com.mjcc.message_board.jooq;


import com.mjcc.message_board.jooq.tables.PunishCategory;
import com.mjcc.message_board.jooq.tables.TReply;
import com.mjcc.message_board.jooq.tables.TUserInfo;
import com.mjcc.message_board.jooq.tables.TWordAreaInfo;
import com.mjcc.message_board.jooq.tables.TWords;
import com.mjcc.message_board.jooq.tables.UserShareInfo;
import com.mjcc.message_board.jooq.tables.Witness;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index PUNISH_CATEGORY_PKEY = Indexes0.PUNISH_CATEGORY_PKEY;
    public static final Index T_REPLY_PKEY = Indexes0.T_REPLY_PKEY;
    public static final Index T_USER_INFO_PKEY = Indexes0.T_USER_INFO_PKEY;
    public static final Index T_WORD_AREA_INFO_PKEY = Indexes0.T_WORD_AREA_INFO_PKEY;
    public static final Index T_WORDS_PKEY = Indexes0.T_WORDS_PKEY;
    public static final Index USER_SHARE_INFO_PKEY = Indexes0.USER_SHARE_INFO_PKEY;
    public static final Index WITNESS_PKEY = Indexes0.WITNESS_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index PUNISH_CATEGORY_PKEY = Internal.createIndex("punish_category_pkey", PunishCategory.PUNISH_CATEGORY, new OrderField[] { PunishCategory.PUNISH_CATEGORY.CATEGORY_ID }, true);
        public static Index T_REPLY_PKEY = Internal.createIndex("t_reply_pkey", TReply.T_REPLY, new OrderField[] { TReply.T_REPLY.LR_ID }, true);
        public static Index T_USER_INFO_PKEY = Internal.createIndex("t_user_info_pkey", TUserInfo.T_USER_INFO, new OrderField[] { TUserInfo.T_USER_INFO.OPENID }, true);
        public static Index T_WORD_AREA_INFO_PKEY = Internal.createIndex("t_word_area_info_pkey", TWordAreaInfo.T_WORD_AREA_INFO, new OrderField[] { TWordAreaInfo.T_WORD_AREA_INFO.ARTICLE_ID }, true);
        public static Index T_WORDS_PKEY = Internal.createIndex("t_words_pkey", TWords.T_WORDS, new OrderField[] { TWords.T_WORDS.LW_ID }, true);
        public static Index USER_SHARE_INFO_PKEY = Internal.createIndex("user_share_info_pkey", UserShareInfo.USER_SHARE_INFO, new OrderField[] { UserShareInfo.USER_SHARE_INFO.SHARE_OPENID }, true);
        public static Index WITNESS_PKEY = Internal.createIndex("witness_pkey", Witness.WITNESS, new OrderField[] { Witness.WITNESS.SHARE_OPENID }, true);
    }
}
