/*
 * This file is generated by jOOQ.
 */
package com.mjcc.message_board.jooq;


import com.mjcc.message_board.jooq.tables.PunishCategory;
import com.mjcc.message_board.jooq.tables.TReply;
import com.mjcc.message_board.jooq.tables.TUserInfo;
import com.mjcc.message_board.jooq.tables.TWordAreaInfo;
import com.mjcc.message_board.jooq.tables.TWords;
import com.mjcc.message_board.jooq.tables.UserShareInfo;
import com.mjcc.message_board.jooq.tables.Witness;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = -1004694168;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * 惩罚类目表
     */
    public final PunishCategory PUNISH_CATEGORY = com.mjcc.message_board.jooq.tables.PunishCategory.PUNISH_CATEGORY;

    /**
     * The table <code>public.t_reply</code>.
     */
    public final TReply T_REPLY = com.mjcc.message_board.jooq.tables.TReply.T_REPLY;

    /**
     * The table <code>public.t_user_info</code>.
     */
    public final TUserInfo T_USER_INFO = com.mjcc.message_board.jooq.tables.TUserInfo.T_USER_INFO;

    /**
     * The table <code>public.t_word_area_info</code>.
     */
    public final TWordAreaInfo T_WORD_AREA_INFO = com.mjcc.message_board.jooq.tables.TWordAreaInfo.T_WORD_AREA_INFO;

    /**
     * The table <code>public.t_words</code>.
     */
    public final TWords T_WORDS = com.mjcc.message_board.jooq.tables.TWords.T_WORDS;

    /**
     * 用户分享信息表
     */
    public final UserShareInfo USER_SHARE_INFO = com.mjcc.message_board.jooq.tables.UserShareInfo.USER_SHARE_INFO;

    /**
     * 分享关联表
     */
    public final Witness WITNESS = com.mjcc.message_board.jooq.tables.Witness.WITNESS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.T_REPLY_LR_ID_SEQ,
            Sequences.T_WORD_AREA_INFO_ARTICLE_ID_SEQ,
            Sequences.T_WORDS_LW_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            PunishCategory.PUNISH_CATEGORY,
            TReply.T_REPLY,
            TUserInfo.T_USER_INFO,
            TWordAreaInfo.T_WORD_AREA_INFO,
            TWords.T_WORDS,
            UserShareInfo.USER_SHARE_INFO,
            Witness.WITNESS);
    }
}
