/*
 * This file is generated by jOOQ.
 */
package com.mjcc.message_board.jooq;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.t_reply_lr_id_seq</code>
     */
    public static final Sequence<Integer> T_REPLY_LR_ID_SEQ = new SequenceImpl<Integer>("t_reply_lr_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.t_word_area_info_article_id_seq</code>
     */
    public static final Sequence<Integer> T_WORD_AREA_INFO_ARTICLE_ID_SEQ = new SequenceImpl<Integer>("t_word_area_info_article_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.t_words_lw_id_seq</code>
     */
    public static final Sequence<Integer> T_WORDS_LW_ID_SEQ = new SequenceImpl<Integer>("t_words_lw_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));
}
