/*
 * This file is generated by jOOQ.
 */
package com.mjcc.message_board.jooq;


import com.mjcc.message_board.jooq.tables.PunishCategory;
import com.mjcc.message_board.jooq.tables.TReply;
import com.mjcc.message_board.jooq.tables.TUserInfo;
import com.mjcc.message_board.jooq.tables.TWordAreaInfo;
import com.mjcc.message_board.jooq.tables.TWords;
import com.mjcc.message_board.jooq.tables.UserShareInfo;
import com.mjcc.message_board.jooq.tables.Witness;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * 惩罚类目表
     */
    public static final PunishCategory PUNISH_CATEGORY = com.mjcc.message_board.jooq.tables.PunishCategory.PUNISH_CATEGORY;

    /**
     * The table <code>public.t_reply</code>.
     */
    public static final TReply T_REPLY = com.mjcc.message_board.jooq.tables.TReply.T_REPLY;

    /**
     * The table <code>public.t_user_info</code>.
     */
    public static final TUserInfo T_USER_INFO = com.mjcc.message_board.jooq.tables.TUserInfo.T_USER_INFO;

    /**
     * The table <code>public.t_word_area_info</code>.
     */
    public static final TWordAreaInfo T_WORD_AREA_INFO = com.mjcc.message_board.jooq.tables.TWordAreaInfo.T_WORD_AREA_INFO;

    /**
     * The table <code>public.t_words</code>.
     */
    public static final TWords T_WORDS = com.mjcc.message_board.jooq.tables.TWords.T_WORDS;

    /**
     * 用户分享信息表
     */
    public static final UserShareInfo USER_SHARE_INFO = com.mjcc.message_board.jooq.tables.UserShareInfo.USER_SHARE_INFO;

    /**
     * 分享关联表
     */
    public static final Witness WITNESS = com.mjcc.message_board.jooq.tables.Witness.WITNESS;
}
